# Generated by Django 6.0.5 on 2026-06-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_member_unique_together_alter_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mention', 'Mention'), ('assignment', 'Assignment'), ('project', 'Project'), ('sprint', 'Sprint'), ('comment', 'Comment')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('related_task_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_project_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_as_actor', to='core.member')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
