# Generated by Django 6.0.5 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_unique_together_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_counter',
            field=models.IntegerField(default=0, help_text='Auto-incrementing counter for task key generation'),
        ),
    ]